In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("D:\\Khoa học dữ liệu\\xiemhoan\\cancer patient data sets.csv")
data

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0        0         P1   33       1              2            4             5   
1        1        P10   17       1              3            1             5   
2        2       P100   35       1              4            5             6   
3        3      P1000   37       1              7            7             7   
4        4       P101   46       1              6            8             7   
..     ...        ...  ...     ...            ...          ...           ...   
995    995       P995   44       1              6            7             7   
996    996       P996   37       2              6            8             7   
997    997       P997   25       2              4            5             6   
998    998       P998   18       2              6            8             7   
999    999       P999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                       4             3                     2  ...        3   
1                       3             4                     2  ...        1   
2                       5             5                     4  ...        8   
3                       7             6                     7  ...        4   
4                       7             7                     6  ...        3   
..                    ...           ...                   ...  ...      ...   
995                     7             7                     6  ...        5   
996                     7             7                     6  ...        9   
997                     5             5                     4  ...        8   
998                     7             7                     6  ...        3   
999                     5             5                     4  ...        8   

     Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0              4                    2         2                      3   
1              3                    7         8                      6   
2              7                    9         2                      1   
3              2                    3         1                      4   
4              2                    4         1                      4   
..           ...                  ...       ...                    ...   
995            3                    2         7                      8   
996            6                    5         7                      2   
997            7                    9         2                      1   
998            2                    4         1                      4   
999            7                    9         2                      1   

     Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                           1              2          3        4     Low  
1                           2              1          7        2  Medium  
2                           4              6          7        2    High  
3                           5              6          7        5    High  
4                           2              4          2        3    High  
..                        ...            ...        ...      ...     ...  
995                         2              4          5        3    High  
996                         4              3          1        4    High  
997                         4              6          7        2    High  
998                         2              4          2        3    High  
999                         4              6          7        2    High  

[1000 rows x 26 columns]

In [2]:
selected_columns = ['Age', 'Gender', 'Air Pollution', 'Genetic Risk', 'chronic Lung Disease',
                    'Smoking', 'Passive Smoker', 'Shortness of Breath', 'Level']
selected_data = data.loc[:, selected_columns]

print(selected_data.head())


   Age  Gender  Air Pollution  Genetic Risk  chronic Lung Disease  Smoking  \
0   33       1              2             3                     2        3   
1   17       1              3             4                     2        2   
2   35       1              4             5                     4        2   
3   37       1              7             6                     7        7   
4   46       1              6             7                     6        8   

   Passive Smoker  Shortness of Breath   Level  
0               2                    2     Low  
1               4                    7  Medium  
2               3                    9    High  
3               7                    3    High  
4               7                    4    High  


In [3]:
# convert column Level(dependent variable) from category to int
selected_data['Level'].unique()
## Now, apply LabelEncoding for this Level column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
selected_data['Level'] = le.fit_transform(selected_data['Level'])

In [4]:
## Spliting the dataset into training and testing
X = selected_data.iloc[:, :-1].values  # other columns
y = selected_data.iloc[:, -1].values  # level
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)


Training data shape: (800, 8)
Testing data shape: (200, 8)


In [5]:
# Feature Scaling of dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("Feature scaling completed.")


Feature scaling completed.


In [6]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()  
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test) 

print("Nhãn dự đoán:", y_pred)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Tỷ lệ chính xác =', accuracy_score(y_test, y_pred))


Nhãn dự đoán: [0 2 2 0 1 2 2 2 2 1 1 0 1 0 0 1 0 2 1 2 0 2 0 0 0 0 1 0 0 2 0 1 1 0 2 1 2
 1 0 1 2 0 1 2 2 1 1 0 0 2 0 2 1 0 1 2 1 1 0 0 1 0 0 0 1 1 1 0 0 0 2 2 2 2
 2 1 1 1 2 0 2 1 2 0 0 2 1 2 2 0 2 1 0 1 2 1 2 0 1 0 2 0 2 1 0 2 0 1 1 0 0
 0 0 2 1 1 1 1 1 2 0 2 0 1 1 2 2 1 1 2 1 2 1 1 0 2 1 2 1 0 2 1 2 2 1 0 2 1
 1 1 1 0 1 0 0 0 1 2 2 2 2 0 0 0 2 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 0 0 2 1 0 0 2]
[[75  0  0]
 [ 0 56 11]
 [ 0 14 44]]
Tỷ lệ chính xác = 0.875


In [7]:
# input
age = 40
gender = 1
air_pollution = 4
genetic_risk = 3
chronic_lung_disease = 2
smoking = 7
passive_smoker = 7
shortness_of_breath = 2

# predict
input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])
prediction = lr.predict(input_data)

print("Level of rate to have lung cancer:", end=' ')
if prediction == 0:
    print('Low')
elif prediction == 1:
    print('Medium')
else:
    print('High')

Level of rate to have lung cancer: Low


In [8]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# Tạo dữ liệu huấn luyện
X_train = np.array([[30, 1, 3, 2, 2, 5, 5, 2], [50, 0, 2, 3, 1, 8, 7, 3], [35, 1, 4, 2, 1, 3, 3, 1]])
y_train = np.array([0, 1, 2])

# Huấn luyện mô hình
lr = LogisticRegression()
lr.fit(X_train, y_train)

# Các giá trị đầu vào
age = 40
gender = 1
air_pollution = 4
genetic_risk = 3
chronic_lung_disease = 2
smoking = 7
passive_smoker = 7
shortness_of_breath = 2

# Chuẩn bị dữ liệu đầu vào
input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])

# Dự đoán mức độ nguy cơ mắc bệnh
prediction = lr.predict(input_data)

# In kết quả dự đoán
print("Mức độ nguy cơ mắc bệnh:", end=' ')
if prediction == 0:
    print('Thấp')
elif prediction == 1:
    print('Trung bình')
else:
    print('Cao')

Mức độ nguy cơ mắc bệnh: Trung bình


In [9]:
# input
age = 55
gender = 0
air_pollution = 2
genetic_risk = 4
chronic_lung_disease = 1
smoking = 5
passive_smoker = 3
shortness_of_breath = 3

# predict
input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])
prediction = lr.predict(input_data)

print("Level of risk to have lung cancer:", end=' ')
if prediction == 0:
    print('Low')
elif prediction == 1:
    print('Medium')
else:
    print('High')

Level of risk to have lung cancer: Medium


In [10]:
# input
age = 45
gender = 1
air_pollution = 3
genetic_risk = 2
chronic_lung_disease = 0
smoking = 6
passive_smoker = 2
shortness_of_breath = 1

# predict
input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])
prediction = lr.predict(input_data)

print("Mức độ nguy cơ mắc bệnh ung thư phổi:", end=' ')
if prediction == 0:
    print('Thấp')
elif prediction == 1:
    print('Trung bình')
else:
    print('Cao')

Mức độ nguy cơ mắc bệnh ung thư phổi: Cao


In [11]:
import numpy as np

# Input
age = int(input("Nhập tuổi: "))
gender = int(input("Nhập giới tính (1 cho nữ, 2 cho nam): "))
air_pollution = int(input("Nhập mức độ ô nhiễm không khí: "))
genetic_risk = int(input("Nhập mức độ nguy cơ di truyền: "))
chronic_lung_disease = int(input("Có bị bệnh phổi mãn tính không? (chọn mức độ 1 đến 9): "))
smoking = int(input("Nhập mức độ hút thuốc: "))
passive_smoker = int(input("Nhập mức độ hút thuốc nghiện: "))
shortness_of_breath = int(input("Có bị khó thở ngắn không? (Nhập mức độ từ 1 đến 9): "))

# Predict
input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])
prediction = lr.predict(input_data)

print("Mức độ nguy cơ mắc ung thư phổi:", end=' ')
if prediction == 0:
    print('Bạn không bị ung thư')
elif prediction == 1:
    print('Bạn có nguy cơ bị mắc bệnh , hãy đi khám ')
else:
    print('Bạn có nguy cơ cao bị ung thư phổi , bạn nên đi khám')


Mức độ nguy cơ mắc ung thư phổi: Bạn có nguy cơ cao bị ung thư phổi , bạn nên đi khám


In [12]:
## dao diện bthg
import tkinter as tk
from tkinter import messagebox
import numpy as np

# Hàm dự đoán mức độ nguy cơ mắc bệnh ung thư phổi
def predict_cancer():
    try:
        # Lấy giá trị từ các ô nhập liệu
        age = int(entry_age.get())
        gender = int(entry_gender.get())
        air_pollution = int(entry_air_pollution.get())
        genetic_risk = int(entry_genetic_risk.get())
        chronic_lung_disease = int(entry_chronic_lung_disease.get())
        smoking = int(entry_smoking.get())
        passive_smoker = int(entry_passive_smoker.get())
        shortness_of_breath = int(entry_shortness_of_breath.get())

        # Tạo mảng dữ liệu đầu vào
        input_data = np.array([[age, gender, air_pollution, genetic_risk, chronic_lung_disease, smoking, passive_smoker, shortness_of_breath]])

        # Dự đoán mức độ nguy cơ
        prediction = lr.predict(input_data)

        # Hiển thị kết quả
        messagebox.showinfo("Kết quả", f"Mức độ nguy cơ mắc bệnh ung thư phổi: {prediction[0]}")
    except ValueError:
        messagebox.showerror("Lỗi", "Vui lòng nhập đúng định dạng cho các trường")

# Tạo cửa sổ giao diện
window = tk.Tk()
window.title("Dự đoán nguy cơ mắc bệnh ung thư phổi")

# Tạo các nhãn và ô nhập liệu cho các thông tin
label_age = tk.Label(window, text="Tuổi:")
label_age.pack()
entry_age = tk.Entry(window)
entry_age.pack()

label_gender = tk.Label(window, text="Giới tính (1: Nữ, 2: Nam):")
label_gender.pack()
entry_gender = tk.Entry(window)
entry_gender.pack()

label_air_pollution = tk.Label(window, text="Mức ô nhiễm không khí:")
label_air_pollution.pack()
entry_air_pollution = tk.Entry(window)
entry_air_pollution.pack()

label_genetic_risk = tk.Label(window, text="Rủi ro di truyền:")
label_genetic_risk.pack()
entry_genetic_risk = tk.Entry(window)
entry_genetic_risk.pack()

label_chronic_lung_disease = tk.Label(window, text="Bệnh phổi mãn tính:")
label_chronic_lung_disease.pack()
entry_chronic_lung_disease = tk.Entry(window)
entry_chronic_lung_disease.pack()

label_smoking = tk.Label(window, text="Hút thuốc (số năm):")
label_smoking.pack()
entry_smoking = tk.Entry(window)
entry_smoking.pack()

label_passive_smoker = tk.Label(window, text="Người hút thuốc thụ động (số năm):")
label_passive_smoker.pack()
entry_passive_smoker = tk.Entry(window)
entry_passive_smoker.pack()

label_shortness_of_breath = tk.Label(window, text="Khó thở (0: Không, 1: Có):")
label_shortness_of_breath.pack()
entry_shortness_of_breath = tk.Entry(window)
entry_shortness_of_breath.pack()

# Tạo nút dự đoán
btn_predict = tk.Button(window, text="Dự đoán", command=predict_cancer)
btn_predict.pack()

# Khởi chạy giao diện
window.mainloop()